<html lang="ru">
<head>
    <title>Blog of life</title>
    <meta charset="utf8">
    <!--  Подключение стилей  -->
    <style><?= /** @var \Base\View $this */
        $this->renderStyle(); ?>
    </style>
</head>
<body>
<style><?= /** @var \Base\View $this */
    $this->renderStyleBody(); ?></style>
<!-- Вывод сообщений по api -->

<div class="user"> Вы администратор</div>

<div class="homePage">
    <!--  Форма выхода  -->
    <form action="/user/logout">
        <input class="quit" type="submit" value="Выйти">
    </form>
    <!--  Форма добавления пользователя  -->
    <div class="post">
    <form action="addUser" method="post">
        <div class="form-group">
            <label for="add_name">Имя</label>
            <input name="add_name" id="add_name">
        </div>

        <div class="form-group">
            <label for="add_email">Почта</label>
            <input name="add_email" id="add_email">
        </div>

        <div class="form-group">
            <label for="add_password">Пароль</label>
            <input name="add_password" id="add_password">
        </div>

        <div class="form-group">
            <button class="btn" type="submit">Добавить</button>
        </div>
    </form>
    </div>
    <!--  Вывод пользователей  -->
    <div class="border"></div>
    <? if($this->data['users']): ?>
        <?=$this->data['error']?>
        <? foreach ($this->data['users'] as $user): ?>
        <div class="post">
            <form action="saveUser" method="post">
                <div class="form-group">
                    <label for="user_id">Id</label>
                    <input class="user" readonly name="user_id" id="user_id" value="<?=$user['id']?>">
                </div>

                <div class="form-group">
                    <label for="user_name">Имя</label>
                    <input name="user_name" id="user_name" value="<?=htmlspecialchars($user['name'])?>">
                </div>

                <div class="form-group">
                    <label for="user_email">Почта</label>
                    <input name="user_email" id="user_email" value="<?=htmlspecialchars($user['email'])?>">
                </div>

                <div class="form-group">
                    <label for="user_password">Пароль</label>
                    <input name="user_password" id="user_password">
                </div>
                    <div class="users">
                        <button class="btn" type="submit">Сохранить</button>

                        <a class="delete" href="/admin/deleteUser/?id=<?= $user['id'] ?>">Удалить</a>
                    </div>
            </form>
        </div>
        <? endforeach; ?>
    <? endif; ?>

</div>
</body>
</html>