<html lang="ru">
<head>
    <title>Blog of life</title>
    <meta charset="utf8">
    <!--  Подключение стилей  -->
    <style><?= /** @var \Base\View $this */
        $this->renderStyle(); ?></style>
</head>
<style><?= /** @var \Base\View $this */
    $this->renderStyleBody(); ?></style>
<!-- Вывод сообщений по api -->
<? if ($this->data['user']['id'] == ADMIN_ID[0]) : ?>
    <form action="/api/getUserPosts/?user_id=<?= $_GET['id'] ?>" method="get">
        <input type="text" name="user_id" placeholder="Ввести id">
        <input type="submit" value='Найти'>
    </form>
    <a class="btn" href="/admin/index">Редактирование пользователей</a>
<? endif; ?>
<body>
<div class="user"> Ваш email: <?=$this->data['userEmail']?></div>
<div class="homePage">
    <!--  Форма выхода  -->
    <form action="/user/logout">
        <input class="quit" type="submit" value="Выйти">
    </form>
    <!--  Форма ввода сообщений  -->
    <form enctype="multipart/form-data" action="/blog/index" method="post">
        <div class="form-group">
            <label for="message">Введите сообщение:</label>
            <textarea class="form-textarea" name="message" placeholder="Ваш текст" id="message"></textarea>
            <label class="labelFile" for="file">Прикрепить картинку:</label>
            <input class="btn2" type="file" name="userFile" id="file">
            <input class="btn" type="submit" value="Отправить">
        </div>
    </form>
    <!--  Вывод сообщений  -->
    <div class="border"></div>
    <?=$this->data['error']?>
    <? if(!$this->data['error']): ?>
    <? foreach ($this->data['posts'] as $post): ?>
        <div class="post">
            <span class="postUser">Сообщение от <b><?= $post['userdata']['name']; ?></b> Отправлено <?= $post['send_at']; ?></span>
            <div class="message"><?= $post['message']; ?></div>
            <? if (file_exists($post['image'])): ?>
                <img class="image" src="<?= '/blog/image' ?>/?post_id=<?= $post['image'] ?>" alt="">
            <? endif; ?>
            <? if ($this->data['user']['id'] == ADMIN_ID[0]) : ?>
                <a class="delete" href="/admin/delete/?id=<?= $post['id'] ?>">Удалить</a>
            <? endif; ?>
        </div>
    <? endforeach; ?>
    <? endif; ?>

</div>
</body>
</html>