<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Вход</title>
    <!--  Подключение стилей  -->
    <style><?= /** @var \Base\View $this */$this->renderStyle(); ?></style>
</head>
<body>
<style><?= /** @var \Base\View $this */$this->renderStyleBody(); ?></style>
<div class="register_page">
    <!--  Форма входа  -->
    <h1 class="register-title">Вход в аккаунт</h1>
    <form action="/user/auth" method="post">
        <div class="form-group">
            <input class="input" type="email" name="email" placeholder="Ваш email">
        </div>

        <div class="form-group">
            <input class="input" type="password" name="password" placeholder="Ваш пароль">
        </div>
        <!--  Вывод сообщений об ошибках  -->
        <?php if($this->error): ?>
            <span class="error"><?=$this->error?></span>
        <?php endif; ?>
        <!--  Кнопка входа  -->
        <div class="form-group">
            <button class="btn" type="submit">Войти</button>
        </div>
    </form>
</div>

</body>
</html>