<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../Css/style.css">
    <title>Регистрация</title>
</head>
<body>
<div class="register_page">
    <h1 class="register-title">Регистрация</h1>
    <form action="/user/register" method="post">
        <div class="form-group">
            <input class="input" type="text" name="name" placeholder="Ваше имя">
        </div>

        <div class="form-group">
            <input class="input" type="email" name="email" placeholder="Ваш email">
        </div>

        <div class="form-group">
            <input class="input" type="password" name="password" placeholder="Ваш пароль">
        </div>

        <div class="form-group">
            <input class="input" type="password" name="password-confirm" placeholder="Повторите пароль">
        </div>

        <div class="form-group">
            <button class="btn" type="submit">Зарегистрироваться</button>
        </div>

        <?php if($this->error): ?>
            <span class="error"><?=$this->error?></span>
        <?php endif; ?>

    </form>
</div>

</body>
</html>