<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <!--  Подключение стилей  -->
    <style><?= /** @var \Base\View $this */$this->renderStyle(); ?></style>
</head>
<body>
<style><?= /** @var \Base\View $this */$this->renderStyleBody(); ?></style>
<div class="register_page">
    <!--  Форма регистрации  -->
    <h1 class="register-title">Регистрация</h1>
    <form action="/user/register" method="post">
        <div class="form-group">
            <input class="input" type="text" name="name" placeholder="Ваше имя">
        </div>

        <div class="form-group">
            <input class="input" type="email" name="email" placeholder="Ваш email">
        </div>

        <div class="form-group">
            <input class="input" type="password" name="password" placeholder="Ваш пароль">
        </div>

        <div class="form-group">
            <input class="input" type="password" name="password-confirm" placeholder="Повторите пароль">
        </div>

        <div class="form-group">
            <button class="btn" type="submit">Зарегистрироваться</button>
        </div>
        <!--  Вывод сообщений об ошибках  -->
        <?php if($this->error): ?>
            <div class="form-group"><span class="error"><?=$this->error?></span></div>
        <?php endif; ?>
        <!--  Кнопка входа  -->
        <div class="form-group">
            <a href="/user/authRedirect">Войти</a>
        </div>

    </form>
</div>

</body>
</html>